import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Card, CardTitle, Icon } from '@/components/ui';
import { getCurrentUserOrRedirect } from '@/lib/auth';
import { RegenerateSummaryButton } from './RegenerateSummaryButton';

export default async function SubmissionDetailPage({
  params,
}: {
  params: Promise<{ id: string; submissionId: string }>;
}) {
  const { id, submissionId } = await params;
  const { supabase } = await getCurrentUserOrRedirect();
  const { data: subRaw } = await supabase
    .from('submissions')
    .select(
      '*, teams(id, name, team_members(profiles(full_name, email))), hackathon_tracks(name)',
    )
    .eq('id', submissionId)
    .eq('hackathon_id', id)
    .maybeSingle();

  if (!subRaw) notFound();
  const sub = subRaw as any;

  // Auto-generate AI summary on first view (cached after) — non-blocking.
  if (!sub.ai_summary) {
    try {
      const { summarizeSubmission } = await import('@/lib/summarize');
      const newSummary = await summarizeSubmission(submissionId);
      if (newSummary) sub.ai_summary = newSummary;
    } catch (e) {
      /* swallow — fall back to no summary */
    }
  }

  const team = sub.teams as any;
  const members = (team?.team_members ?? []) as Array<{ profiles: { full_name: string; email: string } | null }>;
  const screenshotUrls = (sub.screenshot_urls ?? []) as string[];

  return (
    <div style={{ display: 'grid', gap: 'var(--space-4)', gridTemplateColumns: 'minmax(0, 2fr) minmax(0, 1fr)' }}>
      <div style={{ display: 'grid', gap: 'var(--space-4)' }}>
        {/* AI summary card */}
        <Card tone="cream">
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
            <Icon.Sparkles size={18} />
            <strong style={{ fontSize: 'var(--font-size-label)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              AI summary
            </strong>
          </div>
          {sub.ai_summary ? (
            <>
              <p style={{ margin: 0, lineHeight: 1.55 }}>{sub.ai_summary}</p>
              <div style={{ marginTop: 'var(--space-3)', display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
                <span style={{ fontSize: 'var(--font-size-caption)', color: 'var(--color-text-muted)' }}>
                  Generated by Claude Haiku · cached
                </span>
                <RegenerateSummaryButton submissionId={submissionId} />
              </div>
            </>
          ) : (
            <>
              <p style={{ margin: 0, color: 'var(--color-text-muted)' }}>
                Couldn&apos;t generate a summary right now.
              </p>
              <RegenerateSummaryButton submissionId={submissionId} />
            </>
          )}
        </Card>

        <Card>
          <Link
            href={`/dashboard/hackathons/${id}/submissions`}
            style={{ fontSize: 'var(--font-size-caption)' }}
          >
            ← All submissions
          </Link>
          <h2 style={{ margin: '8px 0 12px', fontSize: 'var(--font-size-h2)', fontWeight: 800 }}>
            {sub.title}
          </h2>
          <div style={{ display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap', marginBottom: 'var(--space-4)' }}>
            <Badge tone={sub.status === 'submitted' ? 'success' : 'info'}>{sub.status}</Badge>
            {(sub.hackathon_tracks as any)?.name ? <Badge tone="secondary">{(sub.hackathon_tracks as any).name}</Badge> : null}
          </div>
          {sub.description ? (
            <p style={{ whiteSpace: 'pre-wrap', color: 'var(--color-text)' }}>{sub.description}</p>
          ) : null}

          <div style={{ marginTop: 'var(--space-5)', display: 'grid', gap: 'var(--space-2)' }}>
            {sub.github_url ? <LinkRow label="GitHub" href={sub.github_url} /> : null}
            {sub.demo_url ? <LinkRow label="Demo" href={sub.demo_url} /> : null}
            {sub.presentation_url ? <LinkRow label="Presentation" href={sub.presentation_url} /> : null}
            {sub.video_url ? <LinkRow label="Video" href={sub.video_url} /> : null}
          </div>

          {screenshotUrls.length > 0 ? (
            <div style={{ marginTop: 'var(--space-5)' }}>
              <h3 style={{ fontSize: 'var(--font-size-h3)', fontWeight: 800 }}>Screenshots</h3>
              <div style={{ display: 'grid', gap: 'var(--space-3)', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', marginTop: 'var(--space-2)' }}>
                {screenshotUrls.map((url, i) => (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    key={i}
                    src={url}
                    alt={`Screenshot ${i + 1}`}
                    style={{ width: '100%', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)' }}
                  />
                ))}
              </div>
            </div>
          ) : null}
        </Card>
      </div>

      <Card>
        <CardTitle>Team</CardTitle>
        <p style={{ marginTop: 'var(--space-2)', fontWeight: 700 }}>{team?.name ?? '—'}</p>
        <ul style={{ paddingLeft: '1.2em', marginTop: 'var(--space-2)' }}>
          {members.map((m, i) => (
            <li key={i} style={{ marginBottom: 'var(--space-1)' }}>
              {m.profiles?.full_name ?? '—'} <span style={{ color: 'var(--color-text-muted)', fontSize: 'var(--font-size-caption)' }}>· {m.profiles?.email}</span>
            </li>
          ))}
        </ul>
        {sub.submitted_at ? (
          <p style={{ marginTop: 'var(--space-4)', fontSize: 'var(--font-size-caption)', color: 'var(--color-text-muted)' }}>
            Submitted {new Date(sub.submitted_at).toLocaleString()}
          </p>
        ) : null}
      </Card>
    </div>
  );
}

function LinkRow({ label, href }: { label: string; href: string }) {
  return (
    <div style={{ display: 'flex', gap: 'var(--space-3)' }}>
      <strong style={{ width: 120 }}>{label}:</strong>
      <a href={href} target="_blank" rel="noreferrer" style={{ wordBreak: 'break-all' }}>
        {href}
      </a>
    </div>
  );
}
